services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compra-programada-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
